In [1]:
import pandas as pd

In [8]:
df=pd.read_csv("ford_car_reviews.csv",nrows=25)
df=pd.DataFrame(df)
df

,Unnamed: 0,Review_Date,Author_Name,Vehicle_Title,Review_Title,Review,Rating
0,0,on 06/06/18 14:19 PM (PDT),Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,1,on 08/12/17 06:06 AM (PDT),Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wantin...,3.000
2,2,on 06/15/17 05:43 AM (PDT),Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale...,5.000
3,3,on 05/18/17 17:33 PM (PDT),Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( A...,5.000
4,4,on 01/03/16 18:03 PM (PST),One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am ...,5.000
5,5,on 10/24/15 12:40 PM (PDT),Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensor...",3.000
6,6,on 10/29/11 04:57 AM (PDT),amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a S...,4.625
7,7,on 07/25/11 12:15 PM (PDT),dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and ...,4.375
8,8,on 07/21/11 11:28 AM (PDT),ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded ...,3.500
9,9,on 12/06/10 00:00 AM (PST),Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes ...,4.625
10,10,on 10/29/10 00:00 AM (PDT),Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put th...,4.500
11,11,on 08/22/10 17:37 PM (PDT),shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a ...,4.750
12,12,on 08/20/10 10:34 AM (PDT),Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I ...",4.875
13,13,on 07/22/10 15:00 PM (PDT),Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, ...",4.625
14,14,on 06/19/10 10:05 AM (PDT),kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, f...",4.375
15,15,on 06/11/10 17:13 PM (PDT),DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,I drive very little (about 5k miles per year)...,4.375
16,16,on 04/28/10 06:15 AM (PDT),Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I real...,3.750
17,17,on 04/19/10 01:31 AM (PDT),shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is ...,4.000
18,18,on 03/01/10 18:21 PM (PST),DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down a...,4.750
19,19,on 02/24/10 20:54 PM (PST),Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option...,4.000
20,20,on 01/18/10 08:51 AM (PST),ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st ...",3.375
21,21,on 11/28/09 19:36 PM (PST),StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfo...,4.875
22,22,on 11/12/09 08:34 AM (PST),stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the ca...,4.500
23,23,on 09/23/09 09:09 AM (PDT),ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortab...,4.625
24,24,on 08/16/09 21:41 PM (PDT),MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad ...,4.625

In [9]:
df.drop("Unnamed: 0",axis=1,inplace=True)
df

,Review_Date,Author_Name,Vehicle_Title,Review_Title,Review,Rating
0,on 06/06/18 14:19 PM (PDT),Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,on 08/12/17 06:06 AM (PDT),Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wantin...,3.000
2,on 06/15/17 05:43 AM (PDT),Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale...,5.000
3,on 05/18/17 17:33 PM (PDT),Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( A...,5.000
4,on 01/03/16 18:03 PM (PST),One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am ...,5.000
5,on 10/24/15 12:40 PM (PDT),Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensor...",3.000
6,on 10/29/11 04:57 AM (PDT),amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a S...,4.625
7,on 07/25/11 12:15 PM (PDT),dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and ...,4.375
8,on 07/21/11 11:28 AM (PDT),ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded ...,3.500
9,on 12/06/10 00:00 AM (PST),Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes ...,4.625
10,on 10/29/10 00:00 AM (PDT),Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put th...,4.500
11,on 08/22/10 17:37 PM (PDT),shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a ...,4.750
12,on 08/20/10 10:34 AM (PDT),Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I ...",4.875
13,on 07/22/10 15:00 PM (PDT),Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, ...",4.625
14,on 06/19/10 10:05 AM (PDT),kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, f...",4.375
15,on 06/11/10 17:13 PM (PDT),DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,I drive very little (about 5k miles per year)...,4.375
16,on 04/28/10 06:15 AM (PDT),Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I real...,3.750
17,on 04/19/10 01:31 AM (PDT),shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is ...,4.000
18,on 03/01/10 18:21 PM (PST),DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down a...,4.750
19,on 02/24/10 20:54 PM (PST),Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option...,4.000
20,on 01/18/10 08:51 AM (PST),ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st ...",3.375
21,on 11/28/09 19:36 PM (PST),StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfo...,4.875
22,on 11/12/09 08:34 AM (PST),stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the ca...,4.500
23,on 09/23/09 09:09 AM (PDT),ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortab...,4.625
24,on 08/16/09 21:41 PM (PDT),MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad ...,4.625

In [12]:
SYSTEM_PROMPT="You are an Sentiment Analyzer Assistant, your task is to classify the given reviews, also extract the structured output according to the attached schema"
PROMPT="Analyze the sentiment of each review, categorize it as positive, neutral, or negative, and store the result. Extract key pieces of information from each review, such as the pros and cons mentioned, and the specific features the reviewer liked or disliked (e.g., vehicle performance, comfort, price)."

In [11]:
from pydantic import BaseModel, Field

class ReviewSchema(BaseModel):
  Review_Date: str =Field(description="The date of review"),
  Vehicle_Title: str =Field(description="The full name/model of the car"),
  Review_Text: str =Field(description="The compelete review provided by the user"),
  Sentiment : str =Field(description="The overall sentiment : Positive, Negative or Neutral"),
  Pros: str =Field(description="All pros separated by commas, and each of them in quotes, return None if not present "),
  Cons: str =Field(description="All cons separated by commas, and each of them in quotes, return None if not present "),
  Liked_Features: list =Field(description="All features liked by the reviewer, empty if not present "),
  Disliked_Features: list =Field(description="All features liked by the reviewer, empty if not present ")

In [13]:
import os, json, re, getpass
from dotenv import load_dotenv

load_dotenv( override=True)

True

In [14]:
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("GROQ API Key: ")

In [15]:
from langchain.chat_models import init_chat_model
model_name = "openai/gpt-oss-120b" ##set GPT OSS 120B as the LLM for this lab

In [16]:
#Initialize LLM without native support
llm = init_chat_model(model_name, 
                      model_provider="groq")

In [17]:
llm.invoke('Hi,who are you')

AIMessage(content='Hello! I’m ChatGPT, an AI language model created by OpenAI. I’m here to help answer questions, brainstorm ideas, explain concepts, or just have a friendly chat—whatever you need. How can I assist you today?', additional_kwargs={'reasoning_content': 'The user asks "Hi, who are you". We need to respond as ChatGPT. Provide a friendly introduction. No disallowed content.'}, response_metadata={'token_usage': {'completion_tokens': 86, 'prompt_tokens': 76, 'total_tokens': 162, 'completion_time': 0.180036283, 'prompt_time': 0.003093399, 'queue_time': 0.402785189, 'total_time': 0.183129682, 'completion_tokens_details': {'reasoning_tokens': 29}}, 'model_name': 'openai/gpt-oss-120b', 'system_fingerprint': 'fp_e1a78f200e', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None}, id='run--77e2b601-4d5f-49e6-a217-1f29ee1bb686-0', usage_metadata={'input_tokens': 76, 'output_tokens': 86, 'total_tokens': 162})

In [19]:
from langchain_core.output_parsers import JsonOutputParser
parser = JsonOutputParser(pydantic_object=ReviewSchema)

In [21]:
chain = llm | parser

In [30]:
test=df.iloc[0]

In [32]:
#Get response
llm_response = chain.invoke(PROMPT+str(test))
print(llm_response)

{'review_id': 0, 'review_date': '2018-06-06T14:19:00-07:00', 'author_name': 'Vicki', 'vehicle_title': '2006 Ford Mustang Coupe GT Premium 2dr Coupe', 'review_title': '2006 Mustang GT', 'review_text': 'Doesn’t disappoint', 'rating': 5.0, 'sentiment': 'positive', 'category': 'positive', 'pros': ['Overall satisfaction – the car lives up to expectations', 'Implied strong performance typical of GT Mustang'], 'cons': [], 'liked_features': ['Performance', 'Premium feel / driving enjoyment'], 'disliked_features': []}

In [33]:
results=[]
for item in df:
    llm_response=chain.invoke(PROMPT+str(item))
    results.append(llm_response)

results

OutputParserException: Invalid json output: Sure! I’m ready to analyze the reviews for you. Please provide the reviews (including the review text and, if available, the review date), and I’ll:

1. Determine the overall sentiment (positive / neutral / negative).
2. Extract the key pros and cons.
3. Identify the specific features the reviewer liked or disliked (e.g., performance, comfort, price, technology, fuel‑efficiency, etc.).
4. Return the results in a structured format (JSON) that you can easily store or import elsewhere.

Just paste the reviews (one per line, or as a list) and I’ll get to work.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE